#!/bin/bash

path=$(dirname $0)
mathbuntuLocal="/opt/mathbuntu"

###############################################################
# Check for internet connection. No sense in going on if none #
###############################################################
echo -n "Checking for internet connection..."
up=`ping -c 1 -W 2 google.com -q 2> /dev/null`
if [ -z "$up" ]; then
	up=`ping -c 1 -W 2 yahoo.com -q 2> /dev/null`
fi
if [ -z "$up" ]; then
	echo "None found."
	echo
	echo "It seems this computer is not connected to the internet.
	A live connection is required for installation.
	Exiting now. Bye."
	echo
	exit 1
fi
echo "OK."
echo
echo "This script will install a number of mathematical software titles"
echo "on your computer. You need to have administrative privileges to"
echo "do so. The account you set up when you installed *buntu has such"
echo "privileges. If you are running this from another account, you"
echo "may not have proper administrative rights. We'll find out"
echo "shortly!"
echo
echo "You will soon be asked for your password. You will not see"
echo "anything on screen as you type. This is the normal behavior. Just"
echo "finish typing and hit Return."
echo
echo "Hit Return now to continue."

read junk

sudo rm -f /tmp/mathbuntuVersion
wget -P /tmp https://github.com/lqbrin/mathbuntu/raw/master/mathbuntuVersion &> /dev/null
thisVersion=`cat $path/mathbuntuVersion`
if [ -z "$thisVersion" ]; then
	thisVersion="no-this"
fi
thatVersion=`cat /tmp/mathbuntuVersion`
if [ -z "$thatVersion" ]; then
	thatVersion="no-that"
fi
if [ "$thisVersion" != "$thatVersion" ]; then
	sudo rm -rf /tmp/mathbuntu.tar.gz
	wget -P /tmp https://github.com/lqbrin/mathbuntu/raw/master/mathbuntu.tar.gz &> /dev/null
	if [ ! -f "/tmp/mathbuntu.tar.gz" ]; then
		echo "Unable to get latest installer."
		echo "Perhaps next time..."
	else
		sudo tar -C $mathbuntuLocal -xzf /tmp/mathbuntu.tar.gz &> /dev/null
		path="$mathbuntuLocal/mathbuntu/.files"
	fi
fi

sudo $path/installMathbuntu 2> $path/mathbuntu.err
